spring:
  application:
    name: fiscal-document-adapter
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:mem:fiscaladapter
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

server:
  port: 8080

fiscaladapter:
  ambiente: dev
